blog:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  # 文件上传路径
  upload-path: ${UPLOAD_DIR:upload}
server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        same-site: strict # 严格限制cookie为同域
spring:
  application:
    name: flapypan-blog-api
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/flapypan-blog}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    # 文件上传配置
    multipart:
      enabled: true
      max-file-size: 32MB
      max-request-size: 128MB
  mvc:
    # 此前缀的请求将会由静态资源处理器处理
    static-path-pattern: /static/**
  web:
    resources:
      # 自带的静态资源处理器读取文件的位置
      static-locations: file:${blog.upload-path}
# 日志等级
logging:
  level:
    root: info
# spring doc 配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    persist-authorization: true
  default-consumes-media-type: application/json
  writer-with-order-by-keys: true
# SaToken的配置
sa-token:
  # token名称，也就是cookie的名称
  token-name: blog-token
  # token有效期 7天
  timeout: 604800
  # 关闭多点登录
  is-concurrent: false
  # 多点登录使用同一token
  is-share: true
  # token格式
  token-style: simple-uuid
  # 不打印日志
  is-log: false
  # 不从请求体中读取token
  is-read-body: false
  # 从cookie中读取token
  is-read-cookie: true
  # 不从请求头中读取token
  is-read-header: false
  # 不打印 banner
  is-print: false
